### PR TITLE
Zio actors

### PR DESCRIPTION
**Pull request by nightscape**
This PR adds support for zio-actors which is a relatively new and more functional implementation of an actor system.
The code is not yet cleaned up and some tests are still commented out, but maybe you could already have a broad look at it @nikolakasev.

### CODE REVIEW

**Comment by nikolakasev** [comment]
What is your motivation to use zio-actors?

**Comment by nightscape** [comment]
I'm writing an application that will use ZIO as its effect system and zio-actors seems the natural choice.
Also the API offered by zio-actors allows to write more compact and imo understandable code (see the Akka and the zio-actors version of PetriNetInstance and their tests).

**Comment by nikolakasev** [comment]
Thanks for the explanation, I don't mind the evolution of the library as you are the only one user that I'm aware of at the moment. Maybe an idea to take over the library?

**Comment by nightscape** [comment]
That would be an option from my side. I've forked the repo over to https://github.com/xencura/kagera which would be its future place :smile:
Shall I open a PR which points at the new repo?

**Comment by nikolakasev** [comment]
Please, do. I will then delete the repository on my side.

**Comment by nightscape** [comment]
Hi @nikolakasev, was just doing a little research:
The best option would be if you transfer the repository to the `xencura` organization:
https://docs.github.com/en/github/administering-a-repository/transferring-a-repository

That should automatically redirect everyone who has a link to this repo to the new repo and the new repo wouldn't be shown as a fork.

**Comment by nightscape** [comment]
Also, it would be great if you could Sonatype ownership of `io.kagera` to `com.xencura`.
I'm just trying to find out how to do this.

**Comment by nightscape** [comment]
I guess you would need to create a ticket [like this](https://issues.sonatype.org/browse/OSSRH-49380) on the Sonatype issue tracker

> I would like to request the transfer of ownership from my account, `???`, to nightscape.
> 
> Group id: io.kagera
> 
> GitHub organization: https://github.com/xencura

**Comment by nikolakasev** [comment]
It's actually @merlijn that will need to request the transfer of ownership. See screenshot:

image

**Comment by nikolakasev** [comment]
I've just reached out to @merlijn and he will get in touch with you, @nightscape.

**Comment by nightscape** [comment]
Perfect, thanks!
Let me know when you've transferred the ownership to xencura so I can accept the transfer invitation 😃

**Comment by merlijn** [comment]
Hi @nightscape,

I am the original author of kagera.

A few years ago I have deleted the repository at https://github.com/merlijn/kagera because all the work had been integrated into https://github.com/ing-bank/baker

I should maybe not have done this since there are still some forks around. I was not aware of anyone using it.

Before I can transfer the namespace ``io.kagera`` you must buy and own the domain. This is a requirement from sonatype: 
https://central.sonatype.org/pages/choosing-your-coordinates.html

I no longer own that domain and I think it is available, so that is an option.

Alternatively, without you buying the domain you can do the following:

1. Let Nikola delete this repo or transfer ownership (making you the new primary source). 
2. Rename the namespace in the project to ``com.github.nightscape.kagera``
3. Open up a ticket for this new namespace on sonatype.

Kind regards,

Merlijn.

**Comment by nightscape** [comment]
Hi @nikolakasev, I had another look at the docs, and you might have problems transferring the repo over to the `xencura` organization because you don't have permissions to create repos there.
Could you transfer it to my user @nightscape? I've renamed my fork of kagera to `kagera.old` so we don't run in naming conflicts.

**Comment by nikolakasev** [comment]
I tried to transfer it to you, @nightscape, but I get the following error: "nightscape already has a repository in the nikolakasev/kagera network". I guess that's because you have a fork of it in your repository. I tried transferring to xencura, but as you predicted, I don't have the rights to write to it. I guess the only option is to first remove your fork?

**Comment by nightscape** [comment]
I had hoped that renaming is sufficient, but looks like Github is too smart for this :wink: 
I just deleted the repo, could you try again?
Thank you!

**Comment by nightscape** [comment]
If that doesn't work you could also transfer it to @jasonfranklin-stokes

**Comment by nikolakasev** [comment]
Yep, now it worked and got a message that the transfer was requested.

**Comment by nightscape** [comment]
Perfect, thanks a lot Nikola!!

**Pull request closed without merging**
